<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="0" runstate="Runnable" testcasecount="3" result="Failed" total="3" passed="1" failed="2" inconclusive="0" skipped="0" asserts="3" engine-version="3.11.1.0" clr-version="4.0.30319.42000" start-time="2020-09-19 13:38:10Z" end-time="2020-09-19 13:38:11Z" duration="1.395904">
  <command-line><![CDATA[C:\Users\egormatveev\Sprint_server\data\solutions\2358\Calculator\test_folder\nunit3-console.exe 1.dll]]></command-line>
  <test-suite type="Assembly" id="0-1004" name="1.dll" fullname="C:\Users\egormatveev\Sprint_server\data\solutions\2358\Calculator\test_folder\1.dll" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2020-09-19 13:38:11Z" end-time="2020-09-19 13:38:11Z" duration="0.095923" total="3" passed="1" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="3">
    <environment framework-version="3.11.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.18362" platform="Win32NT" cwd="C:\Users\egormatveev\Sprint_server\data\solutions\2358\Calculator\test_folder" machine-name="32D2" user="egormatveev" user-domain="32D2" culture="ru-RU" uiculture="ru-RU" os-architecture="x64" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="C:\Users\egormatveev\Sprint_server\data\solutions\2358\Calculator\test_folder" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="RuntimeFramework" value="mono-4.0" />
      <setting name="NumberOfTestWorkers" value="2" />
    </settings>
    <properties>
      <property name="_PID" value="224" />
      <property name="_APPDOMAIN" value="domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1005" name="TestProject2" fullname="TestProject2" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2020-09-19 13:38:11Z" end-time="2020-09-19 13:38:11Z" duration="0.083490" total="3" passed="1" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="3">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestFixture" id="0-1000" name="Tests" fullname="TestProject2.Tests" classname="TestProject2.Tests" runstate="Runnable" testcasecount="3" result="Failed" site="Child" start-time="2020-09-19 13:38:11Z" end-time="2020-09-19 13:38:11Z" duration="0.081391" total="3" passed="1" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="3">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-case id="0-1001" name="Test1" fullname="TestProject2.Tests.Test1" methodname="Test1" classname="TestProject2.Tests" runstate="Runnable" seed="1612807849" result="Passed" start-time="2020-09-19 13:38:11Z" end-time="2020-09-19 13:38:11Z" duration="0.014357" asserts="1" />
        <test-case id="0-1002" name="Test2" fullname="TestProject2.Tests.Test2" methodname="Test2" classname="TestProject2.Tests" runstate="Runnable" seed="1223118636" result="Failed" start-time="2020-09-19 13:38:11Z" end-time="2020-09-19 13:38:11Z" duration="0.016382" asserts="1">
          <failure>
            <message><![CDATA[  Expected: 2
  But was:  3
]]></message>
            <stack-trace><![CDATA[  at TestProject2.Tests.Test2 () [0x00008] in <3daf101c641248d887fd0337773769bf>:0 
]]></stack-trace>
          </failure>
          <assertions>
            <assertion result="Failed">
              <message><![CDATA[  Expected: 2
  But was:  3
]]></message>
              <stack-trace><![CDATA[  at TestProject2.Tests.Test2 () [0x00000] in <3daf101c641248d887fd0337773769bf>:0 
]]></stack-trace>
            </assertion>
          </assertions>
        </test-case>
        <test-case id="0-1003" name="Test3" fullname="TestProject2.Tests.Test3" methodname="Test3" classname="TestProject2.Tests" runstate="Runnable" seed="339650579" result="Failed" start-time="2020-09-19 13:38:11Z" end-time="2020-09-19 13:38:11Z" duration="0.019645" asserts="1">
          <failure>
            <message><![CDATA[  Expected: 5
  But was:  6
]]></message>
            <stack-trace><![CDATA[  at TestProject2.Tests.Test3 () [0x00018] in <3daf101c641248d887fd0337773769bf>:0 
]]></stack-trace>
          </failure>
          <assertions>
            <assertion result="Failed">
              <message><![CDATA[  Expected: 5
  But was:  6
]]></message>
              <stack-trace><![CDATA[  at TestProject2.Tests.Test3 () [0x00000] in <3daf101c641248d887fd0337773769bf>:0 
]]></stack-trace>
            </assertion>
          </assertions>
        </test-case>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>